name: crmit_schedule
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  json_annotation: ^2.0.0
  http: ^0.12.0+1
  flutter_redux: 0.5.3
  flutter_redux_dev_tools: ^0.3.0
  async: 2.0.8
  redux_epics: 0.10.4
  rxdart: ^0.20.0
  path_provider: ^0.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^2.0.3


flutter:
  uses-material-design: true

  fonts:
  - family: google_sans
    fonts:
    - asset: assets/google_sans.ttf