name: crmit_schedule
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  json_annotation: ^2.4.0
  http: ^0.12.0+2
  flutter_redux: 0.5.3
  flutter_redux_dev_tools: ^0.3.0
  async: 2.1.0
  redux_epics: 0.10.6
  rxdart: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.6.1
  json_serializable: ^3.0.0


flutter:
  uses-material-design: true

  fonts:
  - family: google_sans
    fonts:
    - asset: assets/google_sans.ttf