name: crmit_schedule
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  json_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^2.0.3
  http: ^0.12.0+1


flutter:
  uses-material-design: true

  fonts:
  - family: google_sans
    fonts:
    - asset: android/app/src/main/res/font/google_sans.ttf